### ISSUE TITLE
please don't flush the watchdog with logs without helping data

### ISSUE THREAD

**Issue by udisun** [stacksight/drupal#16]
https://github.com/stacksight/drupal/blob/7.x-1.x/stacksight.module#L559
this line will just indicate that that module cron is run.
this is useful for debug but doesn't really shed light on any actual logic this cron handls.
as drupal runs all cron hooks we can rest assure that this module's cron also runs.
try to send some meaningful data.

**Comment by liorkesos** [comment]
This was a debug by me - we can remove this line alltogether if needed.
