### ISSUE TITLE
Stacksight installation does not work

### ISSUE THREAD

**Issue by hermanlinnovate** [stacksight/drupal#19]
Installed on clean drupal, 7.17. after enabling the module, in configuration/development/stacksight screen was empty without instructions or fields to insert token.

**Comment by igor-lemon** [comment]
Installed last module on the latest v7 Drupal, all works well. Record your all steps on a video, because I don't know what doesn't work on your side.

**Comment by igor-lemon** [comment]
Also if you have errors, please, include PHP logs.
