### ISSUE TITLE
remove stackId when it is calculated

### ISSUE THREAD

**Issue by oritpersik** [stacksight/drupal#27]
![image](https://cloud.githubusercontent.com/assets/5158550/14671724/0f8fc416-06fc-11e6-9c4c-d67ed52ec53a.png)

display  stackId field only when APP_ID variable exists

**Comment by igor-lemon** [comment]
Done

**Comment by igor-lemon** [comment]
Done

**Comment by oritpersik** [comment]
implement it in WP also.

**Comment by igor-lemon** [comment]
Done. In Drupal user should will be clear cache after each on/off debug mode.
