### ISSUE TITLE
logs files location

### ISSUE THREAD

**Issue by oritpersik** [stacksight/drupal#33]
normally the web server doesn’t have access to write logs to the module’s directory
check if the logs are supposed to be written ..

**Comment by liorkesos** [comment]
No new log should be created - teh debug mode should replace this format
Lior

On Thu, Jun 2, 2016 at 8:00 PM, Orit Persik notifications@github.com
wrote:

> normally the web server doesn’t have access to write logs to the module’s
> directory
> check if the logs are supposed to be written ..
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/stacksight/drupal/issues/33, or mute the thread
> https://github.com/notifications/unsubscribe/AAO9I4BQBgDBwsiYP9hHl4xdWmb0LZMXks5qHwxJgaJpZM4IsxO2
> .

## 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by igor-lemon** [comment]
@liorkesos You can't replace all in debug mode. As example you cant catch some user events, page events, commentc, etc. through debug tab. I did text logs for these cases

**Comment by liorkesos** [comment]
So dont write log but instead run error_log with stacksight in error format
and it will show in /var/log/apache/error.log

On Thu, Jun 2, 2016 at 8:12 PM, Igor Kozlovsky notifications@github.com
wrote:

> @liorkesos https://github.com/liorkesos You can't replace all in debug
> mode. As example you cant catch some user events, page events, commentc,
> etc. through debug tab. I did text logs for these cases
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/stacksight/drupal/issues/33#issuecomment-223358159,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAO9I6yo7v70LUiTXZNd3aJe1PFdwj46ks5qHw70gaJpZM4IsxO2
> .

## 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by oritpersik** [comment]
@igor-lemon implement it in all platforms (drupal/wordpress etc..)
