### ISSUE TITLE
using $user properties without checking for empty could create php warnings

### ISSUE THREAD

**Issue by udisun** [stacksight/drupal#7]
https://github.com/stacksight/drupal/blob/7.x-1.x/stacksight.module#L173
https://github.com/stacksight/drupal/blob/7.x-1.x/stacksight.module#L195
https://github.com/stacksight/drupal/blob/7.x-1.x/stacksight.module#L216

please change to

``` php
if (!empty($user) && $user->uid) {
```

**Comment by bora89** [comment]
The fun thing is that construction does not guaranty you from throwing php warning.

``` php
ini_set('display_errors', 'On');
error_reporting(E_ALL);

$obj = new stdClass();
$obj->name = 'bora';

if (!empty($obj) && $obj->uid) echo 'expecting to be not empty...';
else echo 'hm, appears to be empty';
```

result: http://joxi.ru/jnAyGyVFkMBpmZ

So, as a solution I picked up the drupal function user_is_logged_in() - that is exactly what I need to know.
